# Generated by Django 4.2.1 on 2023-05-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_card',
            field=models.IntegerField(max_length=16, null=True, verbose_name='کارت بانکی'),
        ),
    ]
