# Generated by Django 4.2.1 on 2023-05-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_bank_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank_card',
            field=models.CharField(max_length=16, null=True, verbose_name='کارت بانکی'),
        ),
    ]
