# Generated by Django 4.2.1 on 2023-05-08 18:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('description', models.TextField(max_length=1000, verbose_name='توضیحات')),
                ('status', models.BooleanField(default=True, verbose_name='نمایش داده شود؟')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='shop.category', verbose_name='زیردسته')),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان  طبقه بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام فایل')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='فایل')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='نام محصول')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات')),
                ('inventory', models.BooleanField(default=True, verbose_name='موجودی در انبار')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('processor_series', models.CharField(max_length=150, verbose_name='نام محصول')),
                ('ram_memory', models.CharField(max_length=2, verbose_name='ظرفیت حافظه RAM')),
                ('gpu_series', models.CharField(max_length=60, verbose_name='پردازنده گرافیکی')),
                ('screen_size', models.CharField(max_length=10, verbose_name='اندازه صفحه نمایش')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('attribute', models.ManyToManyField(related_name='attributes', to='shop.attribute', verbose_name='مشخصات')),
                ('category', models.ManyToManyField(related_name='products', to='shop.category', verbose_name='دسته بندی')),
                ('classification', models.ManyToManyField(related_name='products', to='shop.classification', verbose_name='طبقه بندی')),
                ('images', models.ManyToManyField(related_name='images', to='shop.pictures', verbose_name='تصاویر')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
