# Generated by Django 4.2.1 on 2023-05-10 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_address_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_coupon_remove_category_parent_product_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('paid', 'پرداخت شده'), ('awaiting_payment', 'در انتظار پرداخت'), ('canceled', 'لغو شده')], default='awaiting_payment', max_length=20, verbose_name='وضعیت')),
                ('delivery_date', models.DateTimeField(blank=True, verbose_name='تاریخ تحویل')),
                ('discount', models.IntegerField(blank=True, default=None, null=True, verbose_name='تخفیف')),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.address', verbose_name='آدرس تحویل')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'شفارشات',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.SmallIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product')),
            ],
            options={
                'verbose_name': 'دسته ',
                'verbose_name_plural': 'دسته ها ',
            },
        ),
    ]
